### PR TITLE
Update NPC states when calling `NPCWrapper.set_state(...)` 

### PR DESCRIPTION
**Pull request by lioutasb**
Currently, the replayed states don't get updated when calling `set_state` instead of `step`. This PR fixes this.

### CODE REVIEW

**Comment by adscib** [comment]
Why do we need to update it? And to what? My intention was to keep the NPC state unchaged when `set_state` is called on `NPCWrapper`. Is that not what's happening?

**Comment by lioutasb** [comment]
This is for advancing the replayed states when you use a custom `ReplayWrapper` that is based on `NPCWrapper` such as in driving models. This custom wrapper has its own `time` index that the user has to manually change to reflect the timestep that the replayed states should be changed to before calling `set_state`. An example is if I want to render a sequence of ego-only ego-centered birdviews where I want to pass custom states for the ego agent but the other agents are replayed from a log replay. Currently, if I manually call `set_state` at every time step the other agents will remain stationary using the first log state even though I correctly define `_npc_teleport_to` to set the other agent states based on the custom index. This is because the `set_state` function is not calling the `_npc_teleport_to` function to get and set the states of the other agents (when these states are not `None` of course).

**Comment by adscib** [comment]
Right. This is by design, as calling `set_state` is not supposed to advance NPCs. A typical use case for `set_state` is to adjust positions of agents after `step` to facilitate cosimulation. If I understand correctly, after your change that would result in two time steps for NPCs. Instead of makign this change, can you get around this issue on your end by calling `step` with some dummy action before `set_state`?

**Comment by lioutasb** [comment]
Well, this would solve my specific issue. I still don't get though why the proposed change would affect any of the existing functionality. The change in the code depends on `_npc_teleport_to`. This function on its own doesn't suppose to change the way we decide how the NPC states will be indexed (for example doesn't increase or change the time index in [ReplayWrapper](https://github.com/inverted-ai/torchdrivesim/blob/master/torchdrivesim/behavior/replay.py#L78)) if it's correctly implemented. The same is true for the only other example that uses the NPCWrapper, called [IAIWrapper](https://github.com/inverted-ai/torchdrivesim/blob/master/torchdrivesim/behavior/iai.py#L82). This means that the proposed code change won't have any effect on the states of the other agents. It will either set the other agent states to be the same states as before or it won't be executed at all because `_npc_teleport_to` returns `None` (such as when calling `set_state` after calling `step` in the `IAIWrapper`).

**Comment by adscib** [comment]
Wait, I'm confused. So how does your change modify existing behavior?

**Comment by lioutasb** [comment]
This PR is not meant to break any existing behavior but for allowing me to create this [function](https://github.com/inverted-ai/driving-models/blob/02c36d6129eb14f019295406e0806413326dca9e/driving_models/trainers/clip_trainer.py#L71) from driving models that I can use to render ego birdviews when in `ego_only` mode. Alternatively, I can do what you described before with the dummy actions but I still think intuitively that the `set_state` function should call `_npc_teleport_to` to appropriately update the NPC states (assuming an external factor such as the time index is updated) since you don't have a direct way to trigger that (except for calling `step` which is a hack).

**Comment by adscib** [comment]
So the purpose is to refresh the NPC states in case the NPC wrapper was modified externally? In that case, I would be more inclined to add a function specifically for this purpose, such as `refresh_npc_state`. Calling this inside `set_state` unprompted is rather counterintuitive to me.

**Comment by lioutasb** [comment]
Sure having a `refresh_npc_state` function works as well. Although in my opinion the same argument then applies to the `step` function that modifies variables that can be used by `_npc_teleport_to` outside of the latter function and yet still refreshes the NPC states inside the `step` function.

**Comment by lioutasb** [comment]
I'll make the change so that there is an explicit function `refresh_npc_state` for my purpose.

**Comment by adscib** [comment]
What's the status here? Do we still want this?

**Comment by lioutasb** [comment]
I still think there is a potential use case that can be resolved with the discussion from this PR but I don't need this right now. We can close it and revisit it if needed.

**Pull request closed without merging**
